//Constants

var BASE_URL = "http://192.168.1.100/behealthy/app/";
var BASE_URL_AUTHENTICATION = BASE_URL + "authentication/";
var BASE_URL_PLANS= BASE_URL + "plans/";
var BASE_URL_TRAINER = BASE_URL + "trainer/";
var BASE_URL_RECIPES = BASE_URL + "recipes/";
var BASE_URL_ARTICLE = BASE_URL + "article/";
var BASE_URL_PAGE = BASE_URL + "page/";

export const Constants = {
    SIGN_UP: BASE_URL_AUTHENTICATION + 'signup',
    CHECK_SOCIAL_MEDIA: BASE_URL_AUTHENTICATION + 'checkSocialMediaId',
    LOGIN: BASE_URL_AUTHENTICATION + 'login',
    USER_INFO: BASE_URL_AUTHENTICATION + 'userInfo',
    UPDATE_USER_PIC: BASE_URL_AUTHENTICATION + 'updateProfilePic',
    FORGOT_PASSWORD: BASE_URL_AUTHENTICATION + 'forgotPassword',
    Change_Password: BASE_URL_AUTHENTICATION + 'changePassword',
    LOGOUT: BASE_URL_AUTHENTICATION + 'logout',
    DELETE_ACCOUNT: BASE_URL_AUTHENTICATION + 'deleteAccount',
    GET_GOALS: BASE_URL_AUTHENTICATION + 'getGoals',
    GET_ACTIVITYLEVEL: BASE_URL_AUTHENTICATION + 'getActivityLevel',
    GET_NUTRITIONTYPE: BASE_URL_AUTHENTICATION + 'getNutritionTypes',
    GET_ALLERGIESTYPE: BASE_URL_AUTHENTICATION + 'getAllergies',
    UPDATE_OTHER_INFO: BASE_URL_AUTHENTICATION + 'updateOtherInfo',
    GET_ALL_PLANS: BASE_URL_AUTHENTICATION + 'getPlans',
    USER_WEIGHT_LIST: BASE_URL_AUTHENTICATION + 'usersWeightlist',
    UPDATE_WEIGHT: BASE_URL_AUTHENTICATION + 'updateWeight',
    UPDATE_GOAL_WEIGHT: BASE_URL_AUTHENTICATION + 'updateGoalAndWeight',
    ADD_CONTACT_PREFRENCES: BASE_URL_AUTHENTICATION + 'addContactPreferences',
    GET_CONTACT_PREFRENCES: BASE_URL_AUTHENTICATION + 'getContactPreferences',
    
    SUBSCRIPTION: BASE_URL_PLANS + 'subscription',
    CHOOSE_PLAN: BASE_URL_PLANS + 'choosePlan',
    RECOMMENDED_PLAN_LIST: BASE_URL_PLANS + 'recommendedPlanList',
    RECOMMENDED_PLAN_DETAIL: BASE_URL_PLANS + 'recommendedPlanDetail',
    WORKOUT_SCHEDULE: BASE_URL_PLANS + 'workoutSchedule',
    WORKOUT_DAYS: BASE_URL_PLANS + 'workoutDays',
    UPDATE_WORKOUT_DAYS_STATUS: BASE_URL_PLANS + 'updateWorkoutDayStatus',
   
    TRAINER_CATEGORY: BASE_URL_TRAINER + 'getTrainerCategory',
    TRAINER_LIST: BASE_URL_TRAINER + 'list',
    TRAINER_DETAIL: BASE_URL_TRAINER + 'trainerDetail',
    CLIENT_TESTIMONIALS: BASE_URL_TRAINER + 'getClientTestimonials',
    TIPS_AND_ADVISE: BASE_URL_TRAINER + 'getTipsAndAdvise',
    
    RECIPES_LIST: BASE_URL_RECIPES + 'list',
    RECIPES_DETAIL: BASE_URL_RECIPES + 'recipeDetail',
    LIKE_RECIPES: BASE_URL_RECIPES + 'likeRecipe',
    GET_RECIPE_CATEGORY: BASE_URL_RECIPES + 'getRecipeCategory',
    
    GET_ARTICLE_CATEGORY: BASE_URL_ARTICLE + 'getArticleCategory', 
    ARTICLE_LIST: BASE_URL_ARTICLE + 'listing',
    ARTICLE_DETAIL: BASE_URL_ARTICLE + 'articlesDetail', 
    BOOKMARK_ARTICLE: BASE_URL_ARTICLE + 'articleBookmark',
    
    GET_FAQS: BASE_URL_PAGE + 'faqs',
    GET_PRIVACY_POLICY: BASE_URL_PAGE + 'privacypolicy',
    GET_MESSAGE_SUPPORT: BASE_URL_PAGE + 'messagesandsupport',

    KEY_TYPE_CATEGORY_SELECT_DATA: "KEY_TYPE_CATEGORY_SELECT_DATA",
    KEY_TYPE_SUBCATEGORY_SELECT_DATA: "KEY_TYPE_SUBCATEGORY_SELECT_DATA",
}