//String

const String = {
    validate: {
        usernameError: "Please enter your username.",
        passwordError: "Please enter your password.",
        passwordNewError: "Please enter your new password.",
        validUser: "Please check your user id",
        emailError: "Please enter your email address.",
        validEmail: "Please enter valid email address.",
        fullnameError: "Please enter your full name.",
        confirmPassError: "Please enter your confirmation password.",
        missmatchError: "Password mismatch  !!!",
        lengthError: "Your contact must contain 10 characters.",
        contactError:"Please enter your phone number.",
        dateofbirthError:"Please enter your date of birth.",
        fullnameValid:"Letters only",
    },
    authentication:{
        LOGIN_HEADER_TEXT: "LOGIN TO CNQR",
        FORGOT_PASSWORD_HEADER_TEXT: "FORGOT PASSWORD",
        CHANGED_PASWORD_HEADER_TEXT: "CHANGE PASSWORD",
        REGISTER_HEADER_TEXT: "START THE CHANGE",
        REGISTER_SIGNUP_EMAIL: "OR SIGN UP WITH EMAIL",
        REGISTER_FIRST_PAREGRAPH: "Take the first step to unlocking your",
        REGISTER_FIRST_PAREGRAPH2: "potential, if you've already got a CNQR",
        REGISTER_FIRST_PAREGRAPH3: "please log in here",
        REGISTER_CHECKBOX_TEXT: "I want receive emails from CNQR",
    },
    subscription:{
        SUBSCRIPTION_HEADER: '140+ PLANS',
        SUBSCRIPTION_HEADER1: '70+ TRAINERS',
        SUBSCRIPTION_HEADER2: 'UNLIMITED ACCESS',
        SUBSCRIPTION_ABSTRACT: "CNQR will charge the membership fee on a recurring basic until you cancel,Payment will continue unless you desactivate at least 24 hourprior to the end of the current cycle.Any unused potionof your free trial will be forfeitted upon payment ",
        SUBSCRIPTION_SUBSCRIBE_TEXT: "By subscribing you agree to our",
        SUBSCRIPTION_SUBSCRIBE_TEXT1: "terms & Condition",
        SUBSCRIPTION_SUBSCRIBE_TEXT2: ",cookie policy & privacy policy and reprent that you are at least 17 years of age",
    },
    sevenStep:{
        MALEORFEMALE_HEADER: "MALE OR FEMALE?",
        MALEORFEMALE_CONTENT: "Certainly, based on your gender you will need a",
        MALEORFEMALE_CONTENT1: "different approach to your training ;)",
        AGE_HEADER: "HOW OLD ARE YOU?",
        AGE_CONTENT: "This is used to make better suggestion of your",
        AGE_CONTENT1: "workout plans and nutrition approach.",
        WEIGHT_HEADER: "HOW MUCH DO",
        WEIGHT_HEADER1: "YOU WEIGHT?",
        GOAL_HEADER: "YOUR GOAL?",
        GOAL_CONTENT: "Choose one of the following for your",
        GOAL_CONTENT1: "personal fitness goals so we can",
        GOAL_CONTENT2: "recommands the right plan for you.",
        ACTIVITY_HEADER1: "WHAT'S YOUR",
        ACTIVITY_HEADER2: "CURRENT",
        ACTIVITY_HEADER3: "ACTIVITY LEVEL",
        ACTIVITY_CONTENT: "Choose one of the following for your personal fitness",
        ACTIVITY_CONTENT1: "goals so we can recommend the right plans for you.",
        NUTRITION_HEADER: "WHAT'S YOUR",
        NUTRITION_HEADER1: "NUTRITION TYPE",
        NUTRITION_CONTENT: "This is so we can understand how much",
        NUTRITION_CONTENT1: "energy you burn without any exercise",
        ALLERGIES_HEADER: "DO YOU HAVE ANY",
        ALLERGIES_HEADER1: "ALLERGIES?",
        ALLERGIES_CONTENT: "lorem ipsum dolor sit amet,consectetur",
        ALLERGIES_CONTENT1: "adipisicing elit,sed to eiusmod tempor.",
    },
    iconDetailsScreen:{
        PLAN_SELECTION: "SELECT ONE OF MY PLAN",
        QUOTES_TEXT: " HEBA HELPED ME TAKE IT A STEP",
        QUOTES_TEXT1: "FURTHER. I'VE GOT MY BODY AND ",
        QUOTES_TEXT2: "CONFIDENCE BACK",
        CLIENT_FONT: "CLIENT TESTIMONIALS",
        PROFILE_FONT: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,",
        TRAINEE_NAME: "JENNY CLIFFE",
        LOCATION: "LONDON, UK",
        TERMS_CONDITIOIN_TEXT: "TIPS & ADVICE",
        FOLLOW_FONT: "FOLLOW ME",
    },
    choosePlanScreen:{
        CHOOSE_PLAN_FONT: "CHOOSE YOUR PLAN",
        CHOOSE_PLAN_CONTENT: "Start Your Change with one of the following",
        CHOOSE_PLAN_CONTENT1: "selected plans for you created by tge CNQR icons",
    },
    changeYourGoalScreen:{
        HEADER:"SHALL WE CHANGE",
        HEADER_1:"YOUR GOALS?",
        HEADER_CONTENT:"Ready for a new challenge?Lets switch up",
        HEADER_CONTENT2:"your goals and set a new target."
    }
}

export { String }
